version: '3.7'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    expose:
      - 27017
    ports:
      - 27017:27017
    networks: [idprovider-network]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    networks: [idprovider-network]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  idprovider-network:
    driver: bridge